<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>monoteny</string>
	</array>
	<key>name</key>
	<string>Monoteny</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#in_block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#in_array</string>
				</dict>
			</array>
		</dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#in_block</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--.*?$</string>
					<key>name</key>
					<string>comment.line.double-dash</string>
				</dict>
			</array>
		</dict>
		<key>conformance</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(declare)</string>
					<key>name</key>
					<string>storage.type.monoteny</string>
				</dict>
			</array>
		</dict>
		<key>decoration</key>
		<dict>
			<key>begin</key>
			<string>!\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>entity.name.function.decorator.monoteny</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#in_array</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([0-9]+)\.([0-9]+)</string>
					<key>name</key>
					<string>constant.numeric.float.monoteny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([1-9]+[0-9]*|0)</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.monoteny</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\\\(</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#in_object</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^"\\]+</string>
							<key>name</key>
							<string>string.quoted.double</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[!+\-*/&amp;%=&gt;&lt;|.^?][!+\-*/&amp;%=&gt;&lt;|.^?_]*</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else|is|while|loop)\b</string>
					<key>name</key>
					<string>keyword.control.expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>match</key>
			<string>(def)\b+</string>
			<key>name</key>
			<string>storage.type.monoteny</string>
		</dict>
		<key>in_array</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>keyword.other.monoteny</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>keyword.other.monoteny</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>invalid.illegal.object</string>
				</dict>
			</array>
		</dict>
		<key>in_block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reserved</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decoration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conformance</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#trait</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#pattern</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#statement</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>invalid.illegal.block</string>
				</dict>
			</array>
		</dict>
		<key>in_object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.monoteny</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.monoteny</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)\s*(:)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>keyword.other.monoteny</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>invalid.illegal.object</string>
				</dict>
			</array>
		</dict>
		<key>macro</key>
		<dict>
			<key>match</key>
			<string>\w+!</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#in_object</string>
				</dict>
			</array>
		</dict>
		<key>pattern</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(pattern)\b</string>
					<key>name</key>
					<string>storage.type.monoteny</string>
				</dict>
			</array>
		</dict>
		<key>reserved</key>
		<dict>
			<key>match</key>
			<string>(-&gt;|::|;|')</string>
			<key>name</key>
			<string>keyword.other.monoteny</string>
		</dict>
		<key>statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#decoration</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(let|var|upd)\b</string>
					<key>name</key>
					<string>keyword.control.vardef</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(return|yield|continue)\b</string>
					<key>name</key>
					<string>keyword.control.flow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>trait</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(trait)\b</string>
					<key>name</key>
					<string>storage.type.monoteny</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.monoteny</string>
	<key>uuid</key>
	<string>3B9265B5-0CC2-4869-947A-44471511071F</string>
</dict>
</plist>
